### ISSUE TITLE
What happened to the Code of Conduct?

### ISSUE THREAD

**Issue by Mikaela** [privacyguides/.github#1]
[The current Code of Conduct](https://github.com/privacyguides/.github/blob/f44b324ad36d3bc3719594c8254f9ff34a05f129/CODE_OF_CONDUCT.md) is very short, removed enforcement, our responsibilities etc. entirely. What happened to the [previous Code of Conduct](https://web.archive.org/web/20210824161038/https://wiki.privacytools.io/view/PrivacyTools:Code_of_Conduct)?

**Comment by Mikaela** [comment]
@privacyguides/team I find the atmosphere especially within the Matrix rooms has dropped. People are not even trying to communicate positively and there are people literally after drama due to which I just once again left the rooms.

**Comment by dngray** [comment]
This should be restored yes. It was moved to the wiki but that is yet to be restored.

I think we might just move it back to a CODE_OF_CONDUCT.md markdown document in the meantime.

**Comment by dngray** [comment]
@Mikaela do you think there is anything particularly missing from it?

**Comment by Mikaela** [comment]
Discussed in team room. Consensus is that something between the two is desired.
